CreateUsersTable: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `email` varchar(191) not null, `password` varchar(191) not null, `roles` text not null, `default_password` tinyint(1) not null default '1', `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(191) not null, `token` varchar(191) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreateEmployeesTable: create table `employees` (`id` int unsigned not null auto_increment primary key, `first_name` varchar(191) not null, `last_name` varchar(191) not null, `base_salary` decimal(8, 2) not null, `birthdate` date null, `gender` char(1) null, `leaves_per_month` tinyint not null, `dependants` tinyint not null default '0', `registration_number` varchar(191) null, `social_security_number` varchar(191) null, `payment_method` varchar(191) null, `bank_account` varchar(191) null, `office` varchar(191) null, `category` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateContractsTable: create table `contracts` (`id` int unsigned not null auto_increment primary key, `start` date not null, `end` date null, `commentary` text null, `ended` tinyint(1) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateContractsTable: alter table `contracts` add `employee_id` int unsigned not null
CreateContractsTable: alter table `contracts` add constraint `contracts_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreateLeavesTable: create table `leaves` (`id` int unsigned not null auto_increment primary key, `start` date not null, `end` date not null, `reason` text null, `cancelled` tinyint(1) not null, `cancellation_date` date null, `cancellation_reason` text null, `nb_days` tinyint not null, `commentary` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateLeavesTable: alter table `leaves` add `employee_id` int unsigned not null
CreateLeavesTable: alter table `leaves` add constraint `leaves_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreateLoansTable: create table `loans` (`id` int unsigned not null auto_increment primary key, `rate` decimal(8, 2) null, `interest` decimal(8, 2) not null, `capital` decimal(8, 2) not null, `amount` decimal(8, 2) not null, `date` date not null, `commentary` text null, `paid` tinyint(1) null, `cancelled` tinyint(1) null, `cancellation_date` date null, `cancellation_reason` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateLoansTable: alter table `loans` add `employee_id` int unsigned not null
CreateLoansTable: alter table `loans` add constraint `loans_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreateSettingsTable: create table `settings` (`id` int unsigned not null auto_increment primary key, `max_dependants` decimal(8, 2) null, `sum_per_dependants` decimal(8, 2) null, `percentage_personal_fees` decimal(8, 2) null, `threshold` decimal(8, 2) null, `percentage_after_threshold` decimal(8, 2) null, `payroll_tax` text null, `personnal_income_tax` text null, `seniority_bonus` text null, `employer_contribution_rate` decimal(8, 2) null, `employee_contribution_rate` decimal(8, 2) null, `tax_schedule` decimal(8, 2) null, `director` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateAdvancesTable: create table `advances` (`id` int unsigned not null auto_increment primary key, `amount` decimal(8, 2) not null, `date` date not null, `payment_date` date not null, `commentary` text null, `type` varchar(191) not null, `paid` tinyint(1) null, `cancelled` tinyint(1) null, `cancellation_date` date null, `cancellation_reason` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateAdvancesTable: alter table `advances` add `employee_id` int unsigned not null
CreateAdvancesTable: alter table `advances` add constraint `advances_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreatePropertiesTable: create table `properties` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `description` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateEmployeePropertyTable: create table `employee_property` (`value` varchar(191) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateEmployeePropertyTable: alter table `employee_property` add `employee_id` int unsigned not null, add `property_id` int unsigned not null
CreateEmployeePropertyTable: alter table `employee_property` add constraint `employee_property_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreateEmployeePropertyTable: alter table `employee_property` add constraint `employee_property_property_id_foreign` foreign key (`property_id`) references `properties` (`id`)
CreateSalariesTable: create table `salaries` (`id` int unsigned not null auto_increment primary key, `date` date not null, `period_start` date not null, `period_end` date not null, `holidays` text null, `base_salary` decimal(8, 2) null, `ratio` decimal(8, 2) null, `reviewed` tinyint(1) not null, `modification_reason` text null, `leave_balance` decimal(8, 2) not null default '0', `seniority_bonus` tinyint(1) not null default '0', `registration_number` varchar(191) null, `social_security_number` varchar(191) null, `payment_method` varchar(191) null, `bank_account` varchar(191) null, `office` varchar(191) null, `category` varchar(191) null, `dependants` tinyint not null default '0', `openDays` varchar(191) null, `workedDays` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateSalariesTable: alter table `salaries` add `employee_id` int unsigned not null, add `settings_id` int unsigned not null
CreateSalariesTable: alter table `salaries` add constraint `salaries_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`)
CreateSalariesTable: alter table `salaries` add constraint `salaries_settings_id_foreign` foreign key (`settings_id`) references `settings` (`id`)
CreateElementsTable: create table `elements` (`id` int unsigned not null auto_increment primary key, `name` varchar(191) not null, `type` char(191) not null, `description` text null, `prorata` tinyint(1) not null default '1', `irpp` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateElementsTable: alter table `elements` add unique `elements_name_unique`(`name`)
CreateElementSalaryTable: create table `element_salary` (`value` varchar(191) not null, `allowed` tinyint(1) not null, `variable` tinyint(1) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateElementSalaryTable: alter table `element_salary` add `element_id` int unsigned not null, add `salary_id` int unsigned not null
CreateElementSalaryTable: alter table `element_salary` add constraint `element_salary_salary_id_foreign` foreign key (`salary_id`) references `salaries` (`id`)
CreateElementSalaryTable: alter table `element_salary` add constraint `element_salary_element_id_foreign` foreign key (`element_id`) references `elements` (`id`)
CreateGroupsTable: create table `groups` (`id` int unsigned not null auto_increment primary key, `label` varchar(191) not null, `seniority_bonus` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateGroupsTable: alter table `employees` add `group_id` int unsigned null
CreateGroupsTable: alter table `employees` add constraint `employees_group_id_foreign` foreign key (`group_id`) references `groups` (`id`)
CreateElementGroupTable: create table `element_group` (`value` varchar(191) not null, `allowed` tinyint(1) not null, `variable` tinyint(1) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateElementGroupTable: alter table `element_group` add `element_id` int unsigned not null, add `group_id` int unsigned not null
CreateElementGroupTable: alter table `element_group` add constraint `element_group_group_id_foreign` foreign key (`group_id`) references `groups` (`id`)
CreateElementGroupTable: alter table `element_group` add constraint `element_group_element_id_foreign` foreign key (`element_id`) references `elements` (`id`)
CreateLeaveTypesTable: create table `leave_types` (`id` int unsigned not null auto_increment primary key, `label` varchar(191) not null, `deduct` tinyint(1) not null, `description` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateLeaveTypesTable: alter table `leaves` add `leave_type_id` int unsigned not null
CreateLeaveTypesTable: alter table `leaves` add constraint `leaves_leave_type_id_foreign` foreign key (`leave_type_id`) references `leave_types` (`id`)
CreateRepaymentsTable: create table `repayments` (`id` int unsigned not null auto_increment primary key, `amount` decimal(8, 2) not null, `repayment_date` date null, `capital` decimal(8, 2) not null, `interest` decimal(8, 2) not null, `cancelled` tinyint(1) null, `paid` tinyint(1) null, `cancellation_reason` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateRepaymentsTable: alter table `repayments` add `loan_id` int unsigned not null
CreateRepaymentsTable: alter table `repayments` add constraint `repayments_loan_id_foreign` foreign key (`loan_id`) references `loans` (`id`)
